language: python
python:
  - '3.6'
sudo: required
install:
  # Instructions adopted from https://conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create --file envs/environment-lock.yml
  - conda activate evidence_datasource_parsers_lock
script:
  - pytest . --fulltrace
deploy:
  provider: pypi
  user: "${PYPI_USERNAME}"
  password: "${PYPI_PASSWORD}"
  on:
    tags: true
  distributions: "sdist bdist_wheel"

notifications:
  email:
    recipients:
    - ops@opentargets.org
    on_success: never
    on_failure: always
after_success:
  - codecov
