global:
  logDir: gs://otar000-evidence_input/parser_logs
  cacheDir: cache_dir
  schema: https://raw.githubusercontent.com/opentargets/json_schema/master/opentargets.json

cancerBiomarkers:
  inputBucket: gs://otar000-evidence_input/CancerBiomarkers/data_files
  outputBucket: gs://otar000-evidence_input/CancerBiomarkers/json
  # Downloaded separately using wget, because FTP.RemoteProvider cannot handle recursive directory downloads.
  drugIndex: ftp.ebi.ac.uk/pub/databases/opentargets/platform/21.09/output/etl/parquet/diseases
ClinGen:
  webSource: https://search.clinicalgenome.org/kb/gene-validity/download
  inputBucket: gs://otar000-evidence_input/ClinGen/data_files
  outputBucket: gs://otar000-evidence_input/ClinGen/json
CRISPR:
  inputBucket: gs://otar000-evidence_input/CRISPR/data_files
  outputBucket: gs://otar000-evidence_input/CRISPR/json
EPMC:
  inputBucket: gs://open-targets-pre-data-releases/22.02.2/output/literature/cooccurrences
  outputBucket: gs://otar000-evidence_input/EPMC/json
Gene2Phenotype:
  webSource_dd_panel: http://ftp.ebi.ac.uk/pub/databases/gene2phenotype/DD/DDG2P_1_12_2021.csv.gz
  webSource_eye_panel: http://ftp.ebi.ac.uk/pub/databases/gene2phenotype/Eye/EyeG2P_1_12_2021.csv.gz
  webSource_skin_panel: http://ftp.ebi.ac.uk/pub/databases/gene2phenotype/Skin/SkinG2P_1_12_2021.csv.gz
  webSource_cancer_panel: http://ftp.ebi.ac.uk/pub/databases/gene2phenotype/Cancer/CancerG2P_1_12_2021.csv.gz
  inputBucket: gs://otar000-evidence_input/Gene2Phenotype/data_files
  outputBucket: gs://otar000-evidence_input/Gene2Phenotype/json
intOGen:
  inputBucket: gs://otar000-evidence_input/IntOgen/data_files
  outputBucket: gs://otar000-evidence_input/IntOgen/json
  diseaseMapping: resources/cancer2EFO_mappings.tsv
Orphanet:
  webSource: http://www.orphadata.org/data/xml/en_product6.xml
  outputBucket: gs://otar000-evidence_input/Orphanet/json
PanelApp:
  inputBucket: gs://otar000-evidence_input/GenomicsEngland/data_files
  outputBucket: gs://otar000-evidence_input/GenomicsEngland/json
Phenodigm:
  evidenceOutputBucket: gs://otar000-evidence_input/PhenoDigm/json
  phenotypesOutputBucket: gs://otar001-core/MousePhenotypes
PROGENy:
  inputBucket: gs://otar000-evidence_input/PROGENy/data_files
  diseaseMapping: resources/cancer2EFO_mappings.tsv
  pathwayMapping: resources/pathway2Reactome_mappings.tsv
  outputBucket: gs://otar000-evidence_input/PROGENy/json
SLAPEnrich:
  inputBucket: gs://otar000-evidence_input/SLAPEnrich/data_file
  diseaseMapping: resources/cancer2EFO_mappings.tsv
  outputBucket: gs://otar000-evidence_input/SLAPEnrich/json
SysBio:
  inputBucket: gs://otar000-evidence_input/SysBio/data_files
  outputBucket: gs://otar000-evidence_input/SysBio/json
TEP:
  outputBucket: gs://otar001-core/TEPs
TargetSafety:
  adverseEvents: https://raw.githubusercontent.com/opentargets/curation/master/target_safety/adverse_effects.tsv
  safetyRisk: https://raw.githubusercontent.com/opentargets/curation/master/target_safety/safety_risks.tsv
  toxcast: gs://otar001-core/TargetSafety/data_files/toxcast/ToxCast_2021-08-17.tsv
  outputBucket: gs://otar001-core/TargetSafety/json
ChEMBL:
  evidence: gs://otar008-chembl/cttv008-20-01-2022.json.gz
  stopReasonCategories: gs://otar000-evidence_input/ChEMBL/data_files/chembl_predictions-2022-01-24.tsv
  outputBucket: gs://otar000-evidence_input/ChEMBL/json
