global:
  schema_file: 'https://raw.githubusercontent.com/opentargets/json_schema/master/opentargets.json'
  logDir: gs://ot-team/dsuveges/evidence_test/logs

## TODO
## 1. use gs://otar000-evidence_input/ as central bucket for all output
## 2. 


# Parameters for OT Gentics Portal evidence generation:
GeneticsPortal:
  locus2gene: gs://genetics-portal-data/l2g/200127 # 110MB
  toploci: gs://genetics-portal-data/v2d/200207/toploci.parquet  # ~4.9 MB
  study: gs://genetics-portal-data/v2d/200207/studies.parquet # ~1MB
  variantIndex: gs://genetics-portal-data/variant-annotation/190129/variant-annotation.parquet # ~13GB
  ecoCodes: gs://genetics-portal-data/lut/vep_consequences.tsv # 1kb
  outputFile: gs://genetics-portal-analysis/l2g-platform-export/data/geneticsPortal_%s.json.gz
  threshold: 0.05
# Parameters for ClinGen:
ClinGen:
  webSource: https://search.clinicalgenome.org/kb/gene-validity/download
  inputBucket: gs://ot-team/dsuveges/evidence_test/raw_data
  outputBucket: gs://ot-team/dsuveges/evidence_test/processed_evidence